name: FTP Deploy

on:
  push:
    branches:
      - main  # 或者你的默认分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # 可根据需要更改

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy to FTP
        run: |
          sudo apt-get install git-ftp
          git ftp init --user ${{ secrets.FTP_USERNAME }} --passwd ${{ secrets.FTP_PASSWORD }} ftp://your-ftp-server.com/path/to/deployment
        env:
          GIT_FTP_INCLUDED: "dist/**"
